added function to output vpts in csv format
adokter/vol2bird pull request #200
Opened 2023-04-25 18:26 UTC by iskandari

- `--csv` must should come as the last argument. If added, a vpts file will be generated in CSV format according to [vpts data exchange format](https://aloftdata.eu/vpts-csv/)
-  output "filename.csv" must come as the second to last argument
- no checks implemented to verify that data types match

2023-04-25 23:49 UTC, adokter requested changes

2023-04-25 23:49 UTC, adokter commented on src/vol2bird.c
> +        writeCSV(fileVpOut, &alldata, source, fileIn[0], date, time, volume);
this should be brought down, since fileVpOut might be NULL

2023-04-25 23:49 UTC, adokter commented on src/vol2bird.c
> +            result = saveToODIM((RaveCoreObject *)alldata.vp, fileVpOut);
suggest inserting writeCSV function here, determining which format to write to based on extension of fileVpOut

2023-04-25 23:49 UTC, adokter commented on lib/libvol2bird.c
> +#include <assert.h>
do we need this without the vpts csv format assertions?

2023-04-25 23:49 UTC, adokter commented on lib/libvol2bird.h
> +#define MAX_DOUBLE DBL_MAX // Allow Inf in max values
where is this used? does it change behavior of general max function? - Just want to make sure it doesn't change behavior elsewhere

2023-04-26 00:01 UTC, adokter commented
In addition to review comments added above:
1) generated csv contains some unnecessary whitespace from the previous fixed delimited format
2) source_file field should be in quotes, since filenames could theoretically contain a `,` in the filename

2023-05-01 16:28 UTC, iskandari commented
Requested changes made, please review:

- Formatting is based on whether `fileVpOut` contains a .csv string
- All whitespace is removed before writing each new line of the CSV (newlines are preserved)
- Validation code removed

2023-05-09 21:58 UTC, iskandari commented
Copied latest working versions of libvol2bird.c and libvol2bird.h from main in [vol2birdR repo](https://github.com/adokter/vol2birdR)

2023-05-10 15:32 UTC, merged